// src/components/MyComponent.jsx
import { useState } from 'react'

const MyComponent = () => {
	const [isChecked, setIsChecked] = useState(false)
	const [selectedOption, setSelectedOption] = useState('')
	const [textInput, setTextInput] = useState('')

	const handleCheckboxChange = () => {
		setIsChecked(!isChecked)
	}

	const handleRadioChange = (event) => {
		setSelectedOption(event.target.value)
	}

	const handleInputChange = (event) => {
		setTextInput(event.target.value)
	}

	return (
		<div>
			<label>
				<input type="checkbox" checked={isChecked} onChange={handleCheckboxChange} />
				Checkbox
			</label>
			<br />
			<label>
				<input type="radio" value="option1" checked={selectedOption === 'option1'} onChange={handleRadioChange} />
				Option 1
			</label>
			<label>
				<input type="radio" value="option2" checked={selectedOption === 'option2'} onChange={handleRadioChange} />
				Option 2
			</label>
			<br />
			<input type="text" value={textInput} onChange={handleInputChange} />
		</div>
	)
}

export default MyComponent

// src/components/MyComponent.svelte
<script>
	let checkboxValue = false
	let radioValue = ''
	let inputValue = ''

	function handleCheckboxChange(event) {
		checkboxValue = event.target.checked
	}

	function handleRadioChange(event) {
		radioValue = event.target.value
	}

	function handleInputChange(event) {
		inputValue = event.target.value
	}
</script>

<div>
	<label>
		<input type="checkbox" bind:checked={checkboxValue} on:change={handleCheckboxChange} />
		Checkbox
	</label>
</div>

<div>
	<label>
		<input type="radio" value="option1" bind:group={radioValue} on:change={handleRadioChange} />
		Option 1
	</label>
	<label>
		<input type="radio" value="option2" bind:group={radioValue} on:change={handleRadioChange} />
		Option 2
	</label>
</div>

<div>
	<label>
		Text Input:
		<input type="text" bind:value={inputValue} on:input={handleInputChange} />
	</label>
</div>
