// src/components/MyComponent.jsx
import { useState } from 'react'

const MyComponent = () => {
	const [isChecked, setIsChecked] = useState(false)
	const [selectedOption, setSelectedOption] = useState('')
	const [textInput, setTextInput] = useState('')

	const handleCheckboxChange = () => {
		setIsChecked(!isChecked)
	}

	const handleRadioChange = (event) => {
		setSelectedOption(event.target.value)
	}

	const handleInputChange = (event) => {
		setTextInput(event.target.value)
	}

	return (
		<div>
			<label>
				<input type="checkbox" checked={isChecked} onChange={handleCheckboxChange} />
				Checkbox
			</label>
			<br />
			<label>
				<input type="radio" value="option1" checked={selectedOption === 'option1'} onChange={handleRadioChange} />
				Option 1
			</label>
			<label>
				<input type="radio" value="option2" checked={selectedOption === 'option2'} onChange={handleRadioChange} />
				Option 2
			</label>
			<br />
			<input type="text" value={textInput} onChange={handleInputChange} />
		</div>
	)
}

export default MyComponent

// src/components/MyComponent.vue
<template>
	<div>
		<input type="checkbox" v-model="isChecked" />
		<label for="checkbox">Checkbox</label>

		<br />

		<input type="radio" id="option1" value="option1" v-model="selectedOption" />
		<label for="option1">Option 1</label>

		<input type="radio" id="option2" value="option2" v-model="selectedOption" />
		<label for="option2">Option 2</label>

		<br />

		<input type="text" v-model="textInput" />
	</div>
</template>

<script>
export default {
	data() {
		return {
			isChecked: false,
			selectedOption: '',
			textInput: ''
		}
	}
}
</script>

<style scoped>
/* Add your custom styles here */
</style>
